<?php

namespace Vagebond\Runtype\Actions;

use Illuminate\Support\Collection;
use Vagebond\Runtype\Values\TypescriptProperty;
use Vagebond\Runtype\Values\TypescriptType;

class TranspileToTypescript
{
    private Collection $lines;

    public function __construct()
    {
        $this->lines = collect();
        $this->lines->push('// This file is generated by Vagebond\Runtype');
    }

    /** @param  Collection<TypescriptType>  $types */
    public function handle(Collection $types)
    {
        $lines = $this->lines;

        $this->groupTypes($types)->each(function (Collection $groupedTypes, string $group) use (&$lines) {
            $lines->push("declare namespace {$group} {");
            $groupedTypes->each(fn (TypescriptType $type) => $this->processType($type));
            $lines->push('}'.PHP_EOL);
        });

        return $this->lines->join(PHP_EOL);
    }

    /**
     * @param  Collection<TypescriptType>  $types
     * @return Collection<string, Collection<int, TypescriptType>>
     */
    private function groupTypes(Collection $types): Collection
    {
        return $types->mapToGroups(function (TypescriptType $type) {
            return [TypescriptType::determineNamespace($type->getClass()) => $type];
        });
    }

    private function processType(TypescriptType $type): void
    {
        if ($type->listProperties()->isEmpty()) {
            $this->lines->push("\texport type {$type->getName()} = any");

            return;
        }

        $this->lines->push("\texport type {$type->getName()} = {");

        $type->listProperties()->each(fn (TypescriptProperty $property) => $this->processProperty($property));

        $this->lines->push("\t}");
    }

    private function processProperty(TypescriptProperty $property): void
    {
        $this->lines->push("\t\t{$property->getName()}: {$property->getType()};");
    }
}
